@startuml
actor Client
participant Localhost
participant EntryController
participant EntryService

Client --> Localhost : Entry ID
Localhost --> EntryController: Entry ID
EntryController --> EntryService : Entry ID
EntryService --> EntryController : Entry
EntryController --> Localhost : Entry
Localhost --> Client : Entry

@enduml
