@startuml
'https://plantuml.com/class-diagram

class EntryController
class EntryService
class Entry

EntryController -> EntryService: Forward Request information
EntryService -> Entry: Handle Entries

@enduml
